layout_spectrum: 0.4694506546948105
typography_spectrum: 0.07384644565172493
color:
  brandStrength: 0.41531982319429517
  lightness: 0.12670069560408592
  saturation: 0.40213299938477576
  rhythmicContrast: 0.4410489834845066
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
name: Shawn Michael
